name: custom_shape_progress_indicator
description: "A simple package for a custom-shaped progress indicator with multi-platform support"
version: 0.0.2
homepage: https://github.com/badshah-badmas/custom_shape_progress_indicator


environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: